### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by agatiwi** [marcol13/random-cat-picture#1]
I would LOVE to check this project out, but there is no info how can I do this
Therefore I dont know what needs to be installed and how can I show it that great projects to my colleagues at international working environmant

Hope to see the solution to this issue as soon as this is possible

**Comment by marcol13** [comment]
Hello @agatiwi,

actually you don't need anything to check it out. The project is deployed on GitHub pages right [here](https://marcol13.github.io/random-cat-picture/). You can also go there through the link below `Enviroments` section inside repository main page.

Enjoy my project!
